### ISSUE TITLE
Information about team

### ISSUE THREAD

**Issue by ragangithub** [lordksix/catalog-things-ruby#28]
- https://github.com/lordksix/catalog-things-ruby/projects/1
- We are a team of three
- teams
  - member1 (ragangithub)
  - member2 (ShaliniNayan)
  - member3 (lordksix)

**Comment by DammyShittu** [comment]
Hi @ragangithub, @ShaliniNayan and @lordksix,

## Highlights
✔️ Assigning of tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add a description for your task.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/cad10ce1-5dcc-4a75-8b38-be851b301375)

- [ ] Team member 1 is missing this task. Kindly add it.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/d0e2d2c0-a4a2-42cd-aa3c-ad0ce96c48ba)

- [ ] Team member 2 is missing this task. Kindly create it.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/b354f8da-9ff8-41d8-93d3-1f3f821cbc81)

- [ ] Kindly add a description for this task.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/4ae24c37-ea2c-458b-ae77-0732e29b4d47)

- [ ] You have duplicate unit tests for the team member 3. Kindly remove one, preferably the one that has no description.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/130c9940-db87-42db-aac6-701d627d01a4)

- [ ] Team member 3 is missing this task. Kindly create it.

  ![image](https://github.com/lordksix/catalog-things-ruby/assets/54848363/7340ef5a-9576-4c0b-9330-3d8c5f67bcaa)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ragangithub** [comment]
- added a description task for create label class, and add unit test for team member 1
- added option to add and list tasks for all team members
- removed duplicates

**Comment by Gambit142** [comment]
Hi @ragangithub @ShaliniNayan @lordksix 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Created Kanban board from the template given ✔️ 
- All cards are assigned to a team member ✔️ 
- All cards are assigned in a fair way ✔️ 
- All Project requirements are represented by a card ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] The previous reviewer highlighted that the following cards were not created for these project requirements:

- Team Member 1's options for the console application:

![image](https://github.com/lordksix/catalog-things-ruby/assets/77106962/21162044-3d84-411b-8b84-fbd9756ee46d)
 
- Team Member 2's options for the console application:

![image](https://github.com/lordksix/catalog-things-ruby/assets/77106962/a85bdb8f-5c18-47c0-916e-305eabaedda0)

- Team Member 3's options for the console application:

![image](https://github.com/lordksix/catalog-things-ruby/assets/77106962/7c78123f-0924-423e-b5c1-6e428b5f96b7)

#### Please each member should create a card for these requirements. 👍 😎 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lordksix** [comment]
Issues were created for the console application asked for by the reviewers. Now it is associated with the project.

**Comment by muneebulrehman** [comment]
Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Cards added as requested by the previous reviewer
- Good follow-up with the previous reviewers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
